### ISSUE TITLE
Translation to Portuguese

### ISSUE THREAD

**Issue by joaonlopes** [CytronTechnologies/pxt-edubit#3]
Hello,

I bought the EDU:BIT for my 8 year old, but unfortunatly there is no portuguese translation. The manual for the EDU:BIT she can use in german but the UI in the Microsoft MakeCode it would be nicer to have in Portuguese.

I've been working to translate the MakeCode Micro:Bit. Would it be possible for me to work on translating the EDU:BIT (MakeCode blocks and strings) to portuguese?

Thank you

**Comment by kiate** [comment]
Yes, sure! Glad that you are willing to help translating EDUBIT extension to your language. 

Are you familiar with Github fork and pull request? You can actually fork a copy of pxt-edubit, modify the locale folder to add your language and create a pull request (PR). If you are not familiar with Github, we can do it manually and have our engineer to commit to Github after the translation is done. Which would you prefer?

**Comment by joaonlopes** [comment]
It's done. Thank you very much for the help.

**Comment by waiweng83** [comment]
Updated in v1.15.0
